// Import removed since it's now decoupled from newRisksValues logic for generating defaults
export const allPossibleRisks = [
    "Nepřátelské narušení akce / demonstrace / blokáda",
    "Anonymní výhružka (hrozba závažným násilím / výbuchem)",
    "Verbální konflikt",
    "Rvačka / výtržnosti / obtěžování",
    "Útok chladnou zbraní",
    "Střelba",
    "Žhářství",
    "Uložení výbušniny",
    "Výbuch",
    "Závažný vandalismus",
    "Únik škodlivé látky ve vzduchu",
    "Sabotáž techniky",
    "Nelegální použití pyrotechniky",
    "Najetí vozidlem do davu",
    "Extrémní vítr / bouřka",
    "Přívalové srážky / lokální záplava",
    "Úder blesku",
    "Extrémní teplota",
    "Davová panika a nekontrolovaný pohyb lidí",
    "Větší počet zraněných osob (různými vlivy)",
    "Mimořádně závažná událost v blízkosti akce",
    "Dopravní kolaps dopravy v okolí akce",
    "Srážka / hromadný pád závodníků",
    "Vběhnutí diváka nebo zvířete na trať",
    "Sabotáž trati (hřebíky, olej, překážky, natažený drát)",
    "Ztráta dítěte",
    "Nevhodné chování vůči dětem (obtěžování, agrese)",
    "Kybernetický útok na AV/IT infrastrukturu",
    "Zdravotní problémy",
    "Požární poplach (skutečný i falešný)",
    "Selhání evakuace (zablokované únikové cesty)",
    "Pád / zřícení pódia, stage, stanu nebo jiné konstrukce",
    "Elektrotechnická závada (zkrat, požár kabeláže)",
    "Distribuce návykových látek",
    "Střety skupin (hooligans, politika)",
    "Vhazování předmětů na hrací plochu / trať",
    "Invaze diváků na hrací plochu / trať",
    "Rasistické / diskriminační projevy a incidenty",
    "Kolaps bariér / zábran mezi sektory",
    "Požár (stánky, dekorace, technické zázemí)",
    "Padající stromy / velké větve při větru",
    "Utonutí / pád do vody",
    "Omezená / obtížná dostupnost ZZS (terén, vzdálenost)",
    "Úpal, úžeh / Podchlazení"
];


/**
 * Výchozí (defaultní) knihovna bezpečnostních opatření.
 * Slouží jako šablona pro nové uživatele a pro resetování knihovny.
 */
export const defaultMeasures = [
    { id: 'default-1', text: 'Nastavení spolupráce s ostatními měkkými cíli', isPrevention: true, isDetection: true, isReaction: true, applicableRisks: ['Střelba', 'Anonymní výhrůžka', 'Výbušnina umístěná v prostoru akce (NVS)', 'Podezřelé vozidlo', 'Dopravní zácpy a kolaps dopravy v okolí akce', 'Mimořádně závažná událost v blízkosti akce'] },
    { id: 'default-2', text: 'Informování a nastavení spolupráce s policií', isPrevention: true, isDetection: true, isReaction: true, applicableRisks: ['Napadení chladnou zbraní', 'Střelba', 'Anonymní výhrůžka', 'Závažný vandalismus', 'Žhářství', 'Nenávistné narušení akce (protest)', 'Výbušnina umístěná v prostoru akce (NVS)', 'Podezřelé vozidlo', 'Narušení akce extrémním počasím', 'Dopravní zácpy a kolaps dopravy v okolí akce', 'Davová panika a nekontrolovaný pohyb lidí', 'Větší počet zraněných osob (různými vlivy)', 'Mimořádně závažná událost v blízkosti akce', 'Únik škodlivé látky ve vzduchu', 'Sabotáž techniky'] },
    { id: 'default-3', text: 'Jmenná registrace osob', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Napadení chladnou zbraní', 'Střelba', 'Anonymní výhrůžka', 'Závažný vandalismus', 'Žhářství', 'Nenávistné narušení akce (protest)', 'Výbušnina umístěná v prostoru akce (NVS)', 'Davová panika a nekontrolovaný pohyb lidí', 'Sabotáž techniky'] },
    { id: 'default-4', text: 'Kontrola vstupujících osob', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Střelba', 'Žhářství', 'Nenávistné narušení akce (protest)', 'Výbušnina umístěná v prostoru akce (NVS)', 'Podezřelý předmět', 'Davová panika a nekontrolovaný pohyb lidí'] },
    { id: 'default-5', text: 'Kontrola zavazadel', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Napadení chladnou zbraní', 'Střelba', 'Anonymní výhrůžka', 'Žhářství', 'Nenávistné narušení akce (protest)', 'Výbušnina umístěná v prostoru akce (NVS)', 'Podezřelý předmět'] },
    { id: 'default-6', text: 'Kontrola pošty', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Anonymní výhrůžka', 'Výbušnina umístěná v prostoru akce (NVS)', 'Nebezpečná látka ve vzduchu'] },
    { id: 'default-7', text: 'Kontrola vjíždějících vozidel', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Výbušnina umístěná v prostoru akce (NVS)', 'Podezřelé vozidlo'] },
    { id: 'default-8', text: 'Kontrola vozidel v okolí', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Podezřelé vozidlo'] },
    { id: 'default-9', text: 'Kontrola osob bezpečnostním rámem', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Napadení chladnou zbraní', 'Střelba', 'Žhářství', 'Nenávistné narušení akce (protest)', 'Výbušnina umístěná v prostoru akce (NVS)'] },
    { id: 'default-10', text: 'Monitoring prostor CCTV', isPrevention: true, isDetection: true, isReaction: true, applicableRisks: ['Napadení chladnou zbraní', 'Střelba', 'Závažný vandalismus', 'Žhářství', 'Nenávistné narušení akce (protest)', 'Výbušnina umístěná v prostoru akce (NVS)', 'Davová panika a nekontrolovaný pohyb lidí'] },
    { id: 'default-11', text: 'Monitoring počasí', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Narušení akce extrémním počasím', 'Únik škodlivé látky ve vzduchu', 'Extrémní vítr / bouřka', 'Přívalové srážky / lokální záplava', 'Úder blesku', 'Extrémní teplota'] },
    { id: 'default-12', text: 'Použití tísňových tlačítek', isPrevention: false, isDetection: true, isReaction: true, applicableRisks: ['Napadení chladnou zbraní', 'Závažný vandalismus', 'Nenávistné narušení akce (protest)', 'Davová panika a nekontrolovaný pohyb lidí', 'Obtěžování'] },
    { id: 'default-13', text: 'Vymezení neveřejných prostor pomocí ACS', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Anonymní výhrůžka', 'Nenávistné narušení akce (protest)', 'Výbušnina umístěná v prostoru akce (NVS)', 'Sabotáž techniky'] },
    { id: 'default-14', text: 'Zastřežení uzavřených prostor pomocí PZTS (EZS)', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Závažný vandalismus', 'Nenávistné narušení akce (protest)', 'Výbušnina umístěná v prostoru akce (NVS)', 'Davová panika a nekontrolovaný pohyb lidí', 'Sabotáž techniky'] },
    { id: 'default-15', text: 'Přítomnost fyzické ostrahy', isPrevention: true, isDetection: true, isReaction: true, applicableRisks: ['Napadení chladnou zbraní', 'Střelba', 'Závažný vandalismus', 'Nenávistné narušení akce (protest)', 'Davová panika a nekontrolovaný pohyb lidí', 'Větší počet zraněných osob (různými vlivy)', 'Sabotáž techniky'] },
    { id: 'default-16', text: 'Použití zábran proti nájezdu', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Nenávistné narušení akce (protest)', 'Podezřelé vozidlo'] },
    { id: 'default-17', text: 'Použití požární signalizace', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Žhářství', 'Výbuch'] },
    { id: 'default-18', text: 'Vymezení prostoru pomocí oplocenek', isPrevention: true, isDetection: false, isReaction: false, applicableRisks: ['Nenávistné narušení akce (protest)', 'Davová panika a nekontrolovaný pohyb lidí'] },
    { id: 'default-19', text: 'Zdravotnická služba', isPrevention: false, isDetection: true, isReaction: true, applicableRisks: ['Napadení chladnou zbraní', 'Střelba', 'Narušení akce extrémním počasím', 'Davová panika a nekontrolovaný pohyb lidí', 'Větší počet zraněných osob (různými vlivy)', 'Únik škodlivé látky ve vzduchu', 'Extrémní teplota'] },
    { id: 'default-20', text: 'Nastavení procedury evakuace', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Napadení chladnou zbraní', 'Anonymní výhrůžka', 'Žhářství', 'Nenávistné narušení akce (protest)', 'Výbušnina umístěná v prostoru akce (NVS)', 'Výbuch', 'Narušení akce extrémním počasím', 'Mimořádně závažná událost v blízkosti akce', 'Únik škodlivé látky ve vzduchu'] },
    { id: 'default-21', text: 'Nastavení procedury lockdown', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Napadení chladnou zbraní', 'Mimořádně závažná událost v blízkosti akce'] },
    { id: 'default-22', text: 'Příprava krizového týmu', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Napadení chladnou zbraní', 'Střelba', 'Anonymní výhrůžka', 'Závažný vandalismus', 'Žhářství', 'Nenávistné narušení akce (protest)', 'Výbušnina umístěná v prostoru akce (NVS)', 'Davová panika a nekontrolovaný pohyb lidí', 'Větší počet zraněných osob (různými vlivy)', 'Mimořádně závažná událost v blízkosti akce', 'Únik škodlivé látky ve vzduchu', 'Sabotáž techniky'] },
    // --- MOMeC Opatření ---
    { id: 'default-23', text: 'Informační cedulky pro veřejnost', isPrevention: true, isDetection: false, isReaction: false, applicableRisks: ['Davová panika a nekontrolovaný pohyb lidí', 'Větší počet zraněných osob (různými vlivy)'] },
    { id: 'default-24', text: 'Koordinační plán a styčný štáb', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Střelba', 'Výbuch', 'Mimořádně závažná událost v blízkosti akce'] },
    { id: 'default-25', text: 'Směrnice výkonu ostrahy', isPrevention: true, isDetection: true, isReaction: true, applicableRisks: ['Závažný vandalismus', 'Napadení chladnou zbraní', 'Nenávistné narušení akce (protest)'] },
    { id: 'default-26', text: 'Vydání a zveřejnění Návštěvního řádu', isPrevention: true, isDetection: false, isReaction: false, applicableRisks: ['Napadení chladnou zbraní', 'Závažný vandalismus', 'Obtěžování'] },
    { id: 'default-27', text: 'Bezpečnostní pohovor / Behaviorální detekce', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Střelba', 'Anonymní výhrůžka', 'Výbušnina umístěná v prostoru akce (NVS)', 'Sabotáž techniky'] },
    { id: 'default-28', text: 'Procedura pro odložené zavazadlo (5C)', isPrevention: false, isDetection: true, isReaction: true, applicableRisks: ['Výbušnina umístěná v prostoru akce (NVS)', 'Podezřelý předmět'] },
    { id: 'default-29', text: 'Zřízení absorpční zóny u vstupů', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Davová panika a nekontrolovaný pohyb lidí', 'Střelba'] },
    // --- Opatření z Metodiky nastavení bezpečnostního systému ---
    { id: 'default-30', text: 'Ohlašovací povinnosti a administrativa akce', isPrevention: true, isDetection: false, isReaction: false, applicableRisks: ['Mimořádně závažná událost v blízkosti akce', 'Narušení akce extrémním počasím'] },
    { id: 'default-31', text: 'Technicko-bezpečnostní přejímka areálu (HZS, ZZS)', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Žhářství', 'Výbuch', 'Sabotáž techniky', 'Extrémní vítr / bouřka'] },
    { id: 'default-32', text: 'Debriefing a vyhodnocení po akci', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Mimořádně závažná událost v blízkosti akce', 'Davová panika a nekontrolovaný pohyb lidí'] }
];