// Odvozeno z defaultProjectRisksValues – jediný zdroj pravdy pro názvy rizik
import { defaultProjectRisksValues } from './defaultProjectRisks';
export const allPossibleRisks = defaultProjectRisksValues.map(r => r.name);


/**
 * Výchozí (defaultní) knihovna bezpečnostních opatření.
 * Slouží jako šablona pro nové uživatele a pro resetování knihovny.
 *
 * DŮLEŽITÉ: Řetězce v `applicableRisks` musí přesně odpovídat `name` v
 * defaultProjectRisks.js – jinak matching v ProjectMeasures.js selže.
 */
export const defaultMeasures = [
    { id: 'default-1', text: 'Nastavení spolupráce s ostatními měkkými cíli', isPrevention: true, isDetection: true, isReaction: true, applicableRisks: ['Střelba', 'Anonymní výhružka (hrozba závažným násilím / výbuchem)', 'Uložení výbušniny', 'Najetí vozidlem do davu', 'Dopravní kolaps dopravy v okolí akce', 'Mimořádně závažná událost v blízkosti akce', 'Střety skupin (hooligans, politika)'] },
    { id: 'default-2', text: 'Informování a nastavení spolupráce s policií', isPrevention: true, isDetection: true, isReaction: true, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Anonymní výhružka (hrozba závažným násilím / výbuchem)', 'Závažný vandalismus', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Výbuch', 'Nelegální použití pyrotechniky', 'Najetí vozidlem do davu', 'Extrémní vítr / bouřka', 'Přívalové srážky / lokální záplava', 'Úder blesku', 'Extrémní teplota', 'Dopravní kolaps dopravy v okolí akce', 'Davová panika a nekontrolovaný pohyb lidí', 'Větší počet zraněných osob (různými vlivy)', 'Mimořádně závažná událost v blízkosti akce', 'Únik škodlivé látky ve vzduchu', 'Sabotáž techniky', 'Střety skupin (hooligans, politika)', 'Distribuce návykových látek', 'Rasistické / diskriminační projevy a incidenty', 'Ztráta dítěte', 'Omezená / obtížná dostupnost ZZS (terén, vzdálenost)'] },
    { id: 'default-3', text: 'Jmenná registrace osob', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Anonymní výhružka (hrozba závažným násilím / výbuchem)', 'Závažný vandalismus', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Davová panika a nekontrolovaný pohyb lidí', 'Sabotáž techniky', 'Střety skupin (hooligans, politika)', 'Ztráta dítěte'] },
    { id: 'default-4', text: 'Kontrola vstupujících osob', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Nelegální použití pyrotechniky', 'Davová panika a nekontrolovaný pohyb lidí', 'Distribuce návykových látek', 'Vhazování předmětů na hrací plochu / trať', 'Střety skupin (hooligans, politika)'] },
    { id: 'default-5', text: 'Kontrola zavazadel', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Anonymní výhružka (hrozba závažným násilím / výbuchem)', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Nelegální použití pyrotechniky', 'Distribuce návykových látek', 'Vhazování předmětů na hrací plochu / trať'] },
    { id: 'default-6', text: 'Kontrola pošty', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Anonymní výhružka (hrozba závažným násilím / výbuchem)', 'Uložení výbušniny', 'Únik škodlivé látky ve vzduchu'] },
    { id: 'default-7', text: 'Kontrola vjíždějících vozidel', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Uložení výbušniny', 'Najetí vozidlem do davu'] },
    { id: 'default-8', text: 'Kontrola vozidel v okolí', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Uložení výbušniny', 'Najetí vozidlem do davu', 'Sabotáž trati (hřebíky, olej, překážky, natažený drát)'] },
    { id: 'default-9', text: 'Kontrola osob bezpečnostním rámem', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Nelegální použití pyrotechniky', 'Vhazování předmětů na hrací plochu / trať'] },
    { id: 'default-10', text: 'Monitoring prostor CCTV', isPrevention: true, isDetection: true, isReaction: true, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Závažný vandalismus', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Verbální konflikt', 'Rvačka / výtržnosti / obtěžování', 'Nelegální použití pyrotechniky', 'Davová panika a nekontrolovaný pohyb lidí', 'Ztráta dítěte', 'Nevhodné chování vůči dětem (obtěžování, agrese)', 'Zdravotní problémy', 'Selhání evakuace (zablokované únikové cesty)', 'Elektrotechnická závada (zkrat, požár kabeláže)', 'Distribuce návykových látek', 'Střety skupin (hooligans, politika)', 'Vhazování předmětů na hrací plochu / trať', 'Invaze diváků na hrací plochu / trať', 'Rasistické / diskriminační projevy a incidenty', 'Kolaps bariér / zábran mezi sektory', 'Požár (stánky, dekorace, technické zázemí)', 'Utonutí / pád do vody', 'Vběhnutí diváka nebo zvířete na trať', 'Sabotáž trati (hřebíky, olej, překážky, natažený drát)'] },
    { id: 'default-11', text: 'Monitoring počasí', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Extrémní vítr / bouřka', 'Přívalové srážky / lokální záplava', 'Úder blesku', 'Extrémní teplota', 'Únik škodlivé látky ve vzduchu', 'Padající stromy / velké větve při větru', 'Úpal, úžeh / Podchlazení', 'Pád / zřícení pódia, stage, stanu nebo jiné konstrukce'] },
    { id: 'default-12', text: 'Použití tísňových tlačítek', isPrevention: false, isDetection: true, isReaction: true, applicableRisks: ['Útok chladnou zbraní', 'Závažný vandalismus', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Rvačka / výtržnosti / obtěžování', 'Verbální konflikt', 'Davová panika a nekontrolovaný pohyb lidí', 'Nevhodné chování vůči dětem (obtěžování, agrese)', 'Zdravotní problémy', 'Rasistické / diskriminační projevy a incidenty'] },
    { id: 'default-13', text: 'Vymezení neveřejných prostor pomocí ACS', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Anonymní výhružka (hrozba závažným násilím / výbuchem)', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Sabotáž techniky', 'Závažný vandalismus', 'Žhářství'] },
    { id: 'default-14', text: 'Zastřežení uzavřených prostor pomocí PZTS (EZS)', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Závažný vandalismus', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Žhářství', 'Sabotáž techniky', 'Elektrotechnická závada (zkrat, požár kabeláže)', 'Požár (stánky, dekorace, technické zázemí)'] },
    { id: 'default-15', text: 'Přítomnost fyzické ostrahy', isPrevention: true, isDetection: true, isReaction: true, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Závažný vandalismus', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Verbální konflikt', 'Rvačka / výtržnosti / obtěžování', 'Nelegální použití pyrotechniky', 'Davová panika a nekontrolovaný pohyb lidí', 'Větší počet zraněných osob (různými vlivy)', 'Sabotáž techniky', 'Ztráta dítěte', 'Nevhodné chování vůči dětem (obtěžování, agrese)', 'Zdravotní problémy', 'Požární poplach (skutečný i falešný)', 'Selhání evakuace (zablokované únikové cesty)', 'Pád / zřícení pódia, stage, stanu nebo jiné konstrukce', 'Elektrotechnická závada (zkrat, požár kabeláže)', 'Distribuce návykových látek', 'Střety skupin (hooligans, politika)', 'Vhazování předmětů na hrací plochu / trať', 'Invaze diváků na hrací plochu / trať', 'Rasistické / diskriminační projevy a incidenty', 'Kolaps bariér / zábran mezi sektory', 'Požár (stánky, dekorace, technické zázemí)', 'Padající stromy / velké větve při větru', 'Utonutí / pád do vody', 'Vběhnutí diváka nebo zvířete na trať', 'Sabotáž trati (hřebíky, olej, překážky, natažený drát)'] },
    { id: 'default-16', text: 'Použití zábran proti nájezdu', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Nepřátelské narušení akce / demonstrace / blokáda', 'Najetí vozidlem do davu', 'Uložení výbušniny'] },
    { id: 'default-17', text: 'Použití požární signalizace', isPrevention: false, isDetection: true, isReaction: false, applicableRisks: ['Žhářství', 'Výbuch', 'Elektrotechnická závada (zkrat, požár kabeláže)', 'Požár (stánky, dekorace, technické zázemí)', 'Požární poplach (skutečný i falešný)'] },
    { id: 'default-18', text: 'Vymezení prostoru pomocí oplocenek', isPrevention: true, isDetection: false, isReaction: false, applicableRisks: ['Nepřátelské narušení akce / demonstrace / blokáda', 'Davová panika a nekontrolovaný pohyb lidí', 'Najetí vozidlem do davu', 'Invaze diváků na hrací plochu / trať', 'Vběhnutí diváka nebo zvířete na trať', 'Utonutí / pád do vody', 'Střety skupin (hooligans, politika)'] },
    { id: 'default-19', text: 'Zdravotnická služba', isPrevention: false, isDetection: true, isReaction: true, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Extrémní vítr / bouřka', 'Přívalové srážky / lokální záplava', 'Úder blesku', 'Extrémní teplota', 'Davová panika a nekontrolovaný pohyb lidí', 'Větší počet zraněných osob (různými vlivy)', 'Únik škodlivé látky ve vzduchu', 'Srážka / hromadný pád závodníků', 'Zdravotní problémy', 'Nevhodné chování vůči dětem (obtěžování, agrese)', 'Selhání evakuace (zablokované únikové cesty)', 'Pád / zřícení pódia, stage, stanu nebo jiné konstrukce', 'Elektrotechnická závada (zkrat, požár kabeláže)', 'Utonutí / pád do vody', 'Úpal, úžeh / Podchlazení', 'Omezená / obtížná dostupnost ZZS (terén, vzdálenost)', 'Kolaps bariér / zábran mezi sektory', 'Požár (stánky, dekorace, technické zázemí)', 'Padající stromy / velké větve při větru', 'Vběhnutí diváka nebo zvířete na trať'] },
    { id: 'default-20', text: 'Nastavení procedury evakuace', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Útok chladnou zbraní', 'Anonymní výhružka (hrozba závažným násilím / výbuchem)', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Výbuch', 'Extrémní vítr / bouřka', 'Přívalové srážky / lokální záplava', 'Úder blesku', 'Extrémní teplota', 'Davová panika a nekontrolovaný pohyb lidí', 'Mimořádně závažná událost v blízkosti akce', 'Únik škodlivé látky ve vzduchu', 'Požární poplach (skutečný i falešný)', 'Selhání evakuace (zablokované únikové cesty)', 'Pád / zřícení pódia, stage, stanu nebo jiné konstrukce', 'Elektrotechnická závada (zkrat, požár kabeláže)', 'Kolaps bariér / zábran mezi sektory', 'Požár (stánky, dekorace, technické zázemí)', 'Padající stromy / velké větve při větru'] },
    { id: 'default-21', text: 'Nastavení procedury lockdown', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Anonymní výhružka (hrozba závažným násilím / výbuchem)', 'Uložení výbušniny', 'Výbuch', 'Mimořádně závažná událost v blízkosti akce', 'Ztráta dítěte'] },
    { id: 'default-22', text: 'Příprava krizového týmu', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Anonymní výhružka (hrozba závažným násilím / výbuchem)', 'Závažný vandalismus', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Výbuch', 'Nelegální použití pyrotechniky', 'Najetí vozidlem do davu', 'Davová panika a nekontrolovaný pohyb lidí', 'Větší počet zraněných osob (různými vlivy)', 'Mimořádně závažná událost v blízkosti akce', 'Únik škodlivé látky ve vzduchu', 'Sabotáž techniky', 'Sabotáž trati (hřebíky, olej, překážky, natažený drát)', 'Kybernetický útok na AV/IT infrastrukturu', 'Srážka / hromadný pád závodníků', 'Zdravotní problémy', 'Požární poplach (skutečný i falešný)', 'Selhání evakuace (zablokované únikové cesty)', 'Pád / zřícení pódia, stage, stanu nebo jiné konstrukce', 'Elektrotechnická závada (zkrat, požár kabeláže)', 'Distribuce návykových látek', 'Střety skupin (hooligans, politika)', 'Invaze diváků na hrací plochu / trať', 'Rasistické / diskriminační projevy a incidenty', 'Kolaps bariér / zábran mezi sektory', 'Požár (stánky, dekorace, technické zázemí)', 'Utonutí / pád do vody', 'Omezená / obtížná dostupnost ZZS (terén, vzdálenost)', 'Extrémní vítr / bouřka', 'Přívalové srážky / lokální záplava', 'Úder blesku', 'Extrémní teplota'] },
    // --- MOMeC Opatření ---
    { id: 'default-23', text: 'Informační cedulky pro veřejnost', isPrevention: true, isDetection: false, isReaction: false, applicableRisks: ['Davová panika a nekontrolovaný pohyb lidí', 'Větší počet zraněných osob (různými vlivy)', 'Ztráta dítěte', 'Utonutí / pád do vody', 'Úpal, úžeh / Podchlazení', 'Požár (stánky, dekorace, technické zázemí)'] },
    { id: 'default-24', text: 'Koordinační plán a styčný štáb', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Výbuch', 'Dopravní kolaps dopravy v okolí akce', 'Mimořádně závažná událost v blízkosti akce', 'Srážka / hromadný pád závodníků', 'Ztráta dítěte', 'Kybernetický útok na AV/IT infrastrukturu', 'Zdravotní problémy', 'Pád / zřícení pódia, stage, stanu nebo jiné konstrukce', 'Omezená / obtížná dostupnost ZZS (terén, vzdálenost)', 'Padající stromy / velké větve při větru', 'Kolaps bariér / zábran mezi sektory'] },
    { id: 'default-25', text: 'Směrnice výkonu ostrahy', isPrevention: true, isDetection: true, isReaction: true, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Závažný vandalismus', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Verbální konflikt', 'Rvačka / výtržnosti / obtěžování', 'Nevhodné chování vůči dětem (obtěžování, agrese)', 'Rasistické / diskriminační projevy a incidenty', 'Střety skupin (hooligans, politika)', 'Vběhnutí diváka nebo zvířete na trať', 'Invaze diváků na hrací plochu / trať', 'Selhání evakuace (zablokované únikové cesty)', 'Sabotáž trati (hřebíky, olej, překážky, natažený drát)'] },
    { id: 'default-26', text: 'Vydání a zveřejnění Návštěvního řádu', isPrevention: true, isDetection: false, isReaction: false, applicableRisks: ['Útok chladnou zbraní', 'Závažný vandalismus', 'Rvačka / výtržnosti / obtěžování', 'Verbální konflikt', 'Nelegální použití pyrotechniky', 'Distribuce návykových látek', 'Nevhodné chování vůči dětem (obtěžování, agrese)', 'Rasistické / diskriminační projevy a incidenty', 'Vhazování předmětů na hrací plochu / trať', 'Invaze diváků na hrací plochu / trať', 'Utonutí / pád do vody', 'Úpal, úžeh / Podchlazení'] },
    { id: 'default-27', text: 'Bezpečnostní pohovor / Behaviorální detekce', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Útok chladnou zbraní', 'Střelba', 'Anonymní výhružka (hrozba závažným násilím / výbuchem)', 'Žhářství', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Uložení výbušniny', 'Sabotáž techniky', 'Nelegální použití pyrotechniky', 'Distribuce návykových látek', 'Nevhodné chování vůči dětem (obtěžování, agrese)', 'Rasistické / diskriminační projevy a incidenty', 'Střety skupin (hooligans, politika)'] },
    { id: 'default-28', text: 'Procedura pro odložené zavazadlo (5C)', isPrevention: false, isDetection: true, isReaction: true, applicableRisks: ['Uložení výbušniny', 'Anonymní výhružka (hrozba závažným násilím / výbuchem)'] },
    { id: 'default-29', text: 'Zřízení absorpční zóny u vstupů', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Střelba', 'Útok chladnou zbraní', 'Davová panika a nekontrolovaný pohyb lidí', 'Najetí vozidlem do davu', 'Kolaps bariér / zábran mezi sektory', 'Invaze diváků na hrací plochu / trať'] },
    // --- Opatření z Metodiky nastavení bezpečnostního systému ---
    { id: 'default-30', text: 'Ohlašovací povinnosti a administrativa akce', isPrevention: true, isDetection: false, isReaction: false, applicableRisks: ['Mimořádně závažná událost v blízkosti akce', 'Nepřátelské narušení akce / demonstrace / blokáda', 'Dopravní kolaps dopravy v okolí akce', 'Extrémní vítr / bouřka', 'Přívalové srážky / lokální záplava', 'Úder blesku', 'Extrémní teplota', 'Omezená / obtížná dostupnost ZZS (terén, vzdálenost)', 'Úpal, úžeh / Podchlazení'] },
    { id: 'default-31', text: 'Technicko-bezpečnostní přejímka areálu (HZS, ZZS)', isPrevention: true, isDetection: true, isReaction: false, applicableRisks: ['Žhářství', 'Výbuch', 'Sabotáž techniky', 'Extrémní vítr / bouřka', 'Požární poplach (skutečný i falešný)', 'Selhání evakuace (zablokované únikové cesty)', 'Pád / zřícení pódia, stage, stanu nebo jiné konstrukce', 'Elektrotechnická závada (zkrat, požár kabeláže)', 'Kolaps bariér / zábran mezi sektory', 'Požár (stánky, dekorace, technické zázemí)', 'Padající stromy / velké větve při větru', 'Utonutí / pád do vody', 'Kybernetický útok na AV/IT infrastrukturu', 'Omezená / obtížná dostupnost ZZS (terén, vzdálenost)'] },
    { id: 'default-32', text: 'Debriefing a vyhodnocení po akci', isPrevention: true, isDetection: false, isReaction: true, applicableRisks: ['Mimořádně závažná událost v blízkosti akce', 'Davová panika a nekontrolovaný pohyb lidí', 'Větší počet zraněných osob (různými vlivy)', 'Srážka / hromadný pád závodníků', 'Kybernetický útok na AV/IT infrastrukturu', 'Nelegální použití pyrotechniky', 'Distribuce návykových látek', 'Střety skupin (hooligans, politika)', 'Rasistické / diskriminační projevy a incidenty', 'Požár (stánky, dekorace, technické zázemí)', 'Selhání evakuace (zablokované únikové cesty)', 'Kolaps bariér / zábran mezi sektory', 'Pád / zřícení pódia, stage, stanu nebo jiné konstrukce', 'Elektrotechnická závada (zkrat, požár kabeláže)', 'Sabotáž techniky', 'Sabotáž trati (hřebíky, olej, překážky, natažený drát)'] }
];
